name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild
    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-1.3
      with:
        # The pattern of files to upload
        args: build/Release/download-cleaner
